### ISSUE TITLE
Use template-literal instead of EJS

### ISSUE THREAD

**Issue by Drulac** [Mermade/arapaho#2]
[Template Literal](https://github.com/Drulac/template-literal) is fastest, smallest and simplest template engine, because it use JS's literal template feature.

It's  55 times faster than EJS, and it also use less CPU and RAM ressources, so it may be a good idea to use it instead of EJS 😀

**Comment by MikeRalphson** [comment]
Thanks. I think I'll stick with EJS for a number of reasons:

* Maturity
* Compatibility / extended syntax
* License clear and compatible with MIT/BSD code. GPL is not, and your `package.json` still says "UNLICENSED"

Good luck with your project.
